spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookstore"
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-message: always
